server:
  port: 8080
  servlet:
    context-path: /API/v1/
spring:
  datasource:
    username: Dev
    password: auk6
    url: jdbc:postgresql://localhost:5432/webtask
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    database: postgresql
